/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controladores;

import Modelos.FiguraGeometrica;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;

/**
 *
 * @author Santiago D
 */
public class Lienzo extends javax.swing.JPanel {

    private LinkedList<FiguraGeometrica> misFiguras;
    
    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
        this.misFiguras = new LinkedList<>();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawRect(10, 10, 50, 50);
        g.setColor(Color.red);
        g.fillRect(10, 10, 30, 30);
        g.setColor(Color.black);
        g.drawOval(100, 10, 100, 100);
        
        Toolkit t = Toolkit.getDefaultToolkit();
        Image imagen = t.getImage("src/Imagenes/grim-reaper.png");
        g.drawImage(imagen,200,200, 180,180, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
